env:
  global:
  - NDK_VERSION=r12b
  - DATE=$(date +%Y-%m-%d)
  - PACKAGE_VERSION=next-$DATE-$TRAVIS_BUILD_NUMBER
sudo: true
language: android
jdk:
  - oraclejdk8
git:
  submodules: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-21
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs
  - git lfs install
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - wget http://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux-x86_64.zip
  - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.zip
  - "unzip -q android-ndk-$NDK_VERSION-linux-x86_64.zip"
  - "rm -rf android-ndk-$NDK_VERSION-linux-x86_64.zip"
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_NDK_HOME}
script:
  - git lfs pull
  - "./gradlew createPackage -i -PpreReleaseVersion=$PACKAGE_VERSION -PgitCommitVersion=$TRAVIS_COMMIT --stacktrace"
  - echo no | android create avd --force -n Arm21 -t android-21 -b armeabi-v7a -c 12M
  - emulator -avd Arm21 -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - "cd test-app && ./gradlew assembleDebug runtests -PembedBindingGenerator=true --stacktrace"
  - adb -e logcat -d 300
  - cd ..
