language:
    android
android:
    components:
        - platform-tools
        - tools

        - build-tools-22.0.1
        - android-22

        - extra-android-support
        - extra-android-m2repository

        - sys-img-x86_64-android-22
script:
    - gradle packar -PPACKAGE_VERSION=5.5.5

