env:
    global:
        - NDK_VERSION=r10e
sudo: false
language:
    android
jdk:
    - oraclejdk8
git:
    submodules: false
android:
    components:
        - platform-tools
        - tools

        - build-tools-22.0.1
        - android-19

        - extra-android-support
        - extra-android-m2repository

        - sys-img-armeabi-v7a-android-19

before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
    - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
    - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
    - export PATH=${PATH}:${ANDROID_NDK_HOME}

before_script:
    - echo no | android create avd --force -n Arm19 -t android-19 -b armeabi-v7a -c 12M
    - emulator -avd Arm19 -no-skin -no-audio -no-window &
    - android-wait-for-emulator

script:
    - ./gradlew packar -i -PPACKAGE_VERSION=5.5.5 -PcompileSdk=android-19 -PsupportVersion=19.0.0 --stacktrace
    - ./gradlew runtest -PenableTest -PcompileSdk=android-19 -PsupportVersion=19.0.0 -PtargetSdk=19 --stacktrace

