language:
    android

git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
    - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
    - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
    - export PATH=${PATH}:${ANDROID_NDK_HOME}

android:
    components:
        - platform-tools
        - tools

        - build-tools-22.0.1
        - android-22

        - extra-android-support
        - extra-android-m2repository

        - sys-img-x86_64-android-22
script:
    - gradle packar -PPACKAGE_VERSION=5.5.5

